server:
  port: 8084
dotenv:
  enabled: true
  override: true
spring:
  application:
    name: cart-service

  datasource:
    url: ${LOCAL_DB_URL}cart_db
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
resilience4j:
  bulkhead:
    instances:
      productService:
        max-concurrent-calls: 10
        max-wait-duration: 50ms
  circuitbreaker:
    instances:
      productService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
  retry:
    instances:
      productService:
        max-attempts: 3
        wait-duration: 500ms
  ratelimiter:
    instances:
      productService:
        limit-for-period: 50
        limit-refresh-period: 1s
        timeout-duration: 0

product:
  service:
    url: ${PRODUCT_SERVICE_URL}

internal:
  auth:
    token: ${INTERNAL_SERVICE_TOKEN}

logging:
  level:
    io.github.resilience4j: DEBUG